//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rega.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AfiasalesEntities4 : DbContext
    {
        private static AfiasalesEntities4 _instance;
        public AfiasalesEntities4()
            : base("name=AfiasalesEntities4")
        {
        }

        public static AfiasalesEntities4 GetContent()
        {
            if (_instance == null)
                _instance = new AfiasalesEntities4();
            return _instance;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Profil> Profil { get; set; }
    }
}
