//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rega.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profil
    {
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Otjestvo { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
        public string image { get; set; }
    }
}
